version: "3.9"
services:
  database:
    image: postgres:13.6
    volumes:
      - postgres-db:/data/postgres
    environment:
      - POSTGRES_USER=pailot_development
      - POSTGRES_PASSWORD=password
    env_file:
      - .env
    ports:
      - "5432:5432"
volumes:
  postgres-db:
